[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project.scripts]
greet = "odp2md.odp2md:app"


[project.entry-points."pipx.run"]
greetings = "odp2md.odp2md:app"
